### ISSUE TITLE
Delete album prompt page is showing the code for getAlbumsForGenre instead of getAlbum

### ISSUE THREAD

**Issue by vtquan** [theimowski/SuaveMusicStore#8]
In [Delete album prompt](https://theimowski.gitbooks.io/suave-music-store/content/en/delete_album_prompt.html), in the section about adding snippets to handle ``deleteAlbum``, it shows the code for ``getAlbumsForGenre`` which was shown earlier in [Queries](https://theimowski.gitbooks.io/suave-music-store/content/en/queries.html) and not ``getAlbum`` that is needed and is shown in [GitHub](https://github.com/theimowski/SuaveMusicStore/commit/00cfe5df0577742b0e8cc4f1710d30c2ef756f56).

``getAlbum`` is also shown in the next page, [Delete album action](https://theimowski.gitbooks.io/suave-music-store/content/en/delete_album_action.html), but it is in the section for showing ``deleteAlbum`` instead.

**Comment by theimowski** [comment]
Thanks! Corrected and published
